"""followers

Revision ID: 987ff97abcbe
Revises: 9681be76360a
Create Date: 2019-05-09 03:50:28.947656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987ff97abcbe'
down_revision = '9681be76360a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
